const data = [
  "Manufacturing",
  "Construction materials",
  "Electronics and Optics",
  "Food and Beverage",
  "confectionery products",
  "Beverages",
  "fish products",
  "meat products",
  "dairy products",
  "Other",
  "snack food",
  "Furniture",
  "Bathroom/sauna",
  "Bedroom",
  "Childrens Room",
  "Kitchen",
  "Living Room",
  "Office",
  "Other",
  "Outdoor Project",
  "Furniture",
  "Machinery",
  "Machinery components",
  "Machinery Equipments",
  "Manufacture of machinery",
  "Maritime",
  "Aluminium and steel workboats",
  "Boat/Yacht building",
  "Boat/Yacht building",
  "Metal structures",
  "Other",
  "Repair and maintenance service",
  "MetalWorking",
  "Construction of metal structures",
  "Houses and buildings",
  "Metal products",
  "Metal works",
  "CNC-machining",
  "Forgings, Fasteners",
  "Gas, Plasma, Laser cutting",
  "MIG, TIG, Aluminum welding",
  "Plastic and Rubber",
  "Packaging",
  "Plastic goods",
  "Plastic processing technology",
  "Blowing",
  "Moulding",
  "Plastics welding and processing",
  "Plastic profiles",
  "Printing",
  "Advertising",
  "Book/Periodicals printing",
  "Labelling and packaging printing",
  "Textile and Clothing",
  "Clothing",
  "Textile",
  "Wood",
  "Other (Wood)",
  "Wooden building materials",
  "Wooden houses",
  "Other",
  "Creative industries",
  "Energy technology",
  "Environment",
  "Service",
  "Business services",
  "Engineering",
  "Information Technology and Telecommunications",
  "Data processing, Web portals, E-marketing",
  "Programming, Consultancy",
  "Software",
  "Transport and Logistics",
  "Air",
  "Rail",
  "Road",
  "Water",
];

export default data;
